/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane/Drone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Drone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.35, 0.343, 0.615]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.002']}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']}>
          <mesh geometry={nodes.Circle.geometry} material={materials['Material.003']} position={[0.537, 0, -0.067]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh geometry={nodes.Circle002_1.geometry} material={materials['Material.001']} position={[-0.333, 0, 0.427]} rotation={[0, Math.PI / 4, 0]} />
          </mesh>
          <mesh geometry={nodes.Circle001.geometry} material={materials['Material.003']} position={[0.537, 0, -0.067]} rotation={[0, -Math.PI / 4, 0]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Drone.glb')
